### ISSUE TITLE
COCO Cap. Karpathy test CIDEr score is super low

### ISSUE THREAD

**Issue by yushuinanrong** [ylsung/VL_adapter#13]
Hi @ylsung 

Thanks for sharing the codebase. I was trying to reproduce the results from training a single adapter for multiple datasets. I found that after training, the performance on the test set for COCO Captioning dataset is super low, e.g., CIDER is 1.16 while the paper reports 114.9. The validation results looks normal, val CIDER reaches 114 after training. The val/test results for the other 3 dataset seem normal as well. I was using the exact same code you provided for training and followed the instruction to create the environment. Did I miss anything?

**Comment by ylsung** [comment]
Hi,

I think it's because I multiply 100 in validation https://github.com/ylsung/VL_adapter/blob/545fcbbdbbaec4c442de35567f6ae477ff4e8265/VL-T5/src/multitask.py#L533
but didn't do this in testing https://github.com/ylsung/VL_adapter/blob/545fcbbdbbaec4c442de35567f6ae477ff4e8265/VL-T5/src/multitask.py#L631
so your result should be 116. Sorry for the confusion.

**Comment by yushuinanrong** [comment]
That makes sense, thanks!
